#!/usr/bin/env python3
"""Generate src/airports_data.h from the OurAirports airports.csv.

Keeps three classes of airport:
  class 2  large_airport   -> ring + label on the scope
  class 1  medium_airport  -> dot on the scope
  class 0  small_airport   -> NOT drawn; only used for departure inference
                              (origin hints), so small/GA craft that climb out
                              of a local strip can be tagged "From <ident>"

Each airport gets a short display ident (<= 4 chars): IATA when it has one,
otherwise the local code, otherwise the GPS/ICAO code. Rows with no short
ident are dropped — they could never be shown to the user anyway.

Emits int16 lat/lon (degrees * 100), the ident, and the class byte.

Usage:
    python3 tools/gen_airports.py /tmp/airports.csv src/airports_data.h

Source data: OurAirports (public domain). https://ourairports.com/data/
"""
import csv
import sys

SCALE = 100.0
CLASSES = {"large_airport": 2, "medium_airport": 1, "small_airport": 0}


def short_ident(r):
    iata = (r.get("iata_code") or "").strip().upper()
    if 1 <= len(iata) <= 3:
        return iata
    for k in ("local_code", "gps_code"):
        v = (r.get(k) or "").strip().upper()
        if 1 <= len(v) <= 4:
            return v
    return ""


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/airports.csv"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/airports_data.h"

    rows = []
    with open(src, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            cls = CLASSES.get(r["type"])
            if cls is None:
                continue
            ident = short_ident(r)
            if not ident:
                continue
            try:
                lat = float(r["latitude_deg"])
                lon = float(r["longitude_deg"])
            except (ValueError, KeyError):
                continue
            lat_s = max(-9000, min(9000, round(lat * SCALE)))
            lon_s = max(-18000, min(18000, round(lon * SCALE)))
            rows.append((lat_s, lon_s, ident, cls))

    n_by_cls = [sum(1 for r in rows if r[3] == c) for c in (0, 1, 2)]
    with open(dst, "w") as f:
        f.write("// Auto-generated by tools/gen_airports.py — DO NOT EDIT.\n")
        f.write("// Source: OurAirports (public domain).\n")
        f.write("// %d airports (%d large, %d medium, %d small). lat,lon are int16 deg*%d.\n"
                % (len(rows), n_by_cls[2], n_by_cls[1], n_by_cls[0], int(SCALE)))
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define AIRPORT_SCALE %d\n" % int(SCALE))
        f.write("#define AIRPORT_NUM %d\n\n" % len(rows))

        f.write("static const int16_t AIRPORT_LAT[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 18):
            f.write("  " + ",".join(str(r[0]) for r in rows[i:i + 18]) + ",\n")
        f.write("};\n\n")

        f.write("static const int16_t AIRPORT_LON[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 18):
            f.write("  " + ",".join(str(r[1]) for r in rows[i:i + 18]) + ",\n")
        f.write("};\n\n")

        f.write("// 2 = large (ring + ident label), 1 = medium (dot), 0 = small (not drawn;\n")
        f.write("// departure inference only).\n")
        f.write("static const uint8_t AIRPORT_CLASS[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 32):
            f.write("  " + ",".join(str(r[3]) for r in rows[i:i + 32]) + ",\n")
        f.write("};\n\n")

        f.write("// Display ident, <= 4 chars: IATA, else local code, else GPS/ICAO code.\n")
        f.write("static const char AIRPORT_ID[AIRPORT_NUM][5] = {\n")
        for i in range(0, len(rows), 10):
            f.write("  " + ",".join('"%s"' % r[2] for r in rows[i:i + 10]) + ",\n")
        f.write("};\n")

    bytes_total = len(rows) * (2 + 2 + 1 + 5)
    print("airports: %d (%d large, %d medium, %d small)"
          % (len(rows), n_by_cls[2], n_by_cls[1], n_by_cls[0]))
    print("flash:    ~%.1f KB" % (bytes_total / 1024.0))
    print("written:  %s" % dst)


if __name__ == "__main__":
    main()
